### ISSUE TITLE
Disable actions on patondev fork

### ISSUE THREAD

**Issue by npaton** [patondev/speed_dating_human_ai#13]
We only want the deploy action enabled on amaatouq/speed_dating_human_ai so let's disable it on patondev fork. 👍

**Comment by npaton** [comment]
First figure out why it's not working on amaatouq: https://github.com/amaatouq/speed_dating_human_ai/runs/823663200

**Comment by hubertusputu1** [comment]
> First figure out why it's not working on amaatouq: https://github.com/amaatouq/speed_dating_human_ai/runs/823663200

it happened because the `PRODUCTION.JSON` and `TOKEN.JSON` don't exist on the `secrets `settings. I will disable the workflow on the patondev fork after i get access to set settings on the amaatuq's repo.

**Comment by npaton** [comment]
Yeah, no, let's not do anything about this, once they're finished testing we'll just bring this down and they are welcome to change the config if they want to do their own deployment 👍
